baseURL = "https://dunham.io"
title = "Andrew Dunham's Blog"
languageCode = "en-us"
copyright = "Copyright (c) 2012 - 2015, Andrew Dunham"
theme = "purehugo"
pygmentsstyle = "igor"

[author]
name = "Andrew Dunham"

[params]
githubName = "andrew-d"
twitterName = "andrew_dunham"
description = "Tech, life, and more"
